env:
  global:
    - CC_TEST_REPORTER_ID=d20eadb9183f9f1866657be5b5e47b4a2398ff1ea0be29fbd50a26a43ea98b62
language: ruby
dist: trusty
cache:
  bundler: true
rvm:
  - 2.2.7
branches:
  only:
    - master
before_install:
  - uname -a
  - lsb_release -a
  - rvm list
  - unset RAILS_ENV
  - rvm rubygems current
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle install
  - bundle exec danger
script:
  - pwd
notifications:
  webhooks: https://www.travisbuddy.com/
